# Generated by Django 5.2.8 on 2025-11-07 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('custo_unitario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(choices=[('ceo', 'Ceo'), ('diretor', 'Diretor'), ('gestor', 'Gestor'), ('rececionista', 'Rececionista')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_time', models.BooleanField(default=True)),
                ('conta', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_time', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PecaReparacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.peca')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('custo_total', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('aguarda_pecas', 'Aguarda Peças')], max_length=50)),
                ('mecanico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinecourse.mecanico')),
                ('pecas', models.ManyToManyField(through='onlinecourse.PecaReparacao', to='onlinecourse.peca')),
            ],
        ),
        migrations.AddField(
            model_name='pecareparacao',
            name='reparacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.reparacao'),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='carro', max_length=30)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.CharField(max_length=11)),
                ('data_chegada', models.DateField(null=True)),
                ('data_saida', models.DateField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaturas', to='onlinecourse.cliente')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.mecanico')),
            ],
        ),
        migrations.AddField(
            model_name='reparacao',
            name='viatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparacoes', to='onlinecourse.viatura'),
        ),
    ]
